dependencies:
  factories:
    Mezzio\Router\RouterInterface: Articus\PathHandler\RouteInjectionFactory
    Articus\PathHandler\MetadataProviderInterface: Articus\PathHandler\MetadataProvider\Factory\Annotation
    Articus\PathHandler\Handler\PluginManager: Articus\PathHandler\Handler\Factory\PluginManager
    Articus\PathHandler\Consumer\PluginManager: Articus\PathHandler\Consumer\Factory\PluginManager
    Articus\PathHandler\Attribute\PluginManager: Articus\PathHandler\Attribute\Factory\PluginManager
    Articus\PathHandler\Producer\PluginManager: Articus\PathHandler\Producer\Factory\PluginManager

Articus\PathHandler\RouteInjectionFactory:
  paths:
    '/v5':
    - App\Handler\AdAccounts
    - App\Handler\AdAccountsAdAccountId
    - App\Handler\AdAccountsAdAccountIdAdGroups
    - App\Handler\AdAccountsAdAccountIdAdGroupsAnalytics
    - App\Handler\AdAccountsAdAccountIdAdGroupsAudienceSizing
    - App\Handler\AdAccountsAdAccountIdAdGroupsTargetingAnalytics
    - App\Handler\AdAccountsAdAccountIdAdGroupsAdGroupId
    - App\Handler\AdAccountsAdAccountIdAdPreviews
    - App\Handler\AdAccountsAdAccountIdAds
    - App\Handler\AdAccountsAdAccountIdAdsAnalytics
    - App\Handler\AdAccountsAdAccountIdAdsTargetingAnalytics
    - App\Handler\AdAccountsAdAccountIdAdsAdId
    - App\Handler\AdAccountsAdAccountIdAdsCreditDiscounts
    - App\Handler\AdAccountsAdAccountIdAdsCreditRedeem
    - App\Handler\AdAccountsAdAccountIdAnalytics
    - App\Handler\AdAccountsAdAccountIdAudienceInsights
    - App\Handler\AdAccountsAdAccountIdAudiences
    - App\Handler\AdAccountsAdAccountIdAudiencesCustom
    - App\Handler\AdAccountsAdAccountIdAudiencesAudienceId
    - App\Handler\AdAccountsAdAccountIdBidFloor
    - App\Handler\AdAccountsAdAccountIdBillingProfiles
    - App\Handler\AdAccountsAdAccountIdBulkDownload
    - App\Handler\AdAccountsAdAccountIdBulkUpsert
    - App\Handler\AdAccountsAdAccountIdBulkBulkRequestId
    - App\Handler\AdAccountsAdAccountIdCampaigns
    - App\Handler\AdAccountsAdAccountIdCampaignsAnalytics
    - App\Handler\AdAccountsAdAccountIdCampaignsTargetingAnalytics
    - App\Handler\AdAccountsAdAccountIdCampaignsCampaignId
    - App\Handler\AdAccountsAdAccountIdConversionTags
    - App\Handler\AdAccountsAdAccountIdConversionTagsOcpmEligible
    - App\Handler\AdAccountsAdAccountIdConversionTagsPageVisit
    - App\Handler\AdAccountsAdAccountIdConversionTagsConversionTagId
    - App\Handler\AdAccountsAdAccountIdCustomerLists
    - App\Handler\AdAccountsAdAccountIdCustomerListsCustomerListId
    - App\Handler\AdAccountsAdAccountIdEvents
    - App\Handler\AdAccountsAdAccountIdInsightsAudiences
    - App\Handler\AdAccountsAdAccountIdKeywords
    - App\Handler\AdAccountsAdAccountIdKeywordsMetrics
    - App\Handler\AdAccountsAdAccountIdLeadForms
    - App\Handler\AdAccountsAdAccountIdLeadFormsLeadFormId
    - App\Handler\AdAccountsAdAccountIdLeadFormsLeadFormIdTest
    - App\Handler\AdAccountsAdAccountIdLeadsSubscriptions
    - App\Handler\AdAccountsAdAccountIdLeadsSubscriptionsSubscriptionId
    - App\Handler\AdAccountsAdAccountIdMmmReports
    - App\Handler\AdAccountsAdAccountIdOrderLines
    - App\Handler\AdAccountsAdAccountIdOrderLinesOrderLineId
    - App\Handler\AdAccountsAdAccountIdProductGroupPromotions
    - App\Handler\AdAccountsAdAccountIdProductGroupPromotionsProductGroupPromotionId
    - App\Handler\AdAccountsAdAccountIdProductGroupsAnalytics
    - App\Handler\AdAccountsAdAccountIdProductGroupsCatalogs
    - App\Handler\AdAccountsAdAccountIdReports
    - App\Handler\AdAccountsAdAccountIdSandbox
    - App\Handler\AdAccountsAdAccountIdSsioAccounts
    - App\Handler\AdAccountsAdAccountIdSsioInsertionOrders
    - App\Handler\AdAccountsAdAccountIdSsioInsertionOrdersStatus
    - App\Handler\AdAccountsAdAccountIdSsioInsertionOrdersPinOrderIdStatus
    - App\Handler\AdAccountsAdAccountIdSsioOrderLines
    - App\Handler\AdAccountsAdAccountIdTargetingAnalytics
    - App\Handler\AdAccountsAdAccountIdTemplates
    - App\Handler\AdAccountsAdAccountIdTemplatesTemplateIdReports
    - App\Handler\AdAccountsAdAccountIdTermsOfService
    - App\Handler\Boards
    - App\Handler\BoardsBoardId
    - App\Handler\BoardsBoardIdPins
    - App\Handler\BoardsBoardIdSections
    - App\Handler\BoardsBoardIdSectionsSectionId
    - App\Handler\BoardsBoardIdSectionsSectionIdPins
    - App\Handler\Catalogs
    - App\Handler\CatalogsFeeds
    - App\Handler\CatalogsFeedsFeedId
    - App\Handler\CatalogsFeedsFeedIdProcessingResults
    - App\Handler\CatalogsItems
    - App\Handler\CatalogsItemsBatch
    - App\Handler\CatalogsItemsBatchBatchId
    - App\Handler\CatalogsProcessingResultsProcessingResultIdItemIssues
    - App\Handler\CatalogsProductGroups
    - App\Handler\CatalogsProductGroupsProductGroupId
    - App\Handler\CatalogsProductGroupsProductGroupIdProductCounts
    - App\Handler\CatalogsProductGroupsProductGroupIdProducts
    - App\Handler\CatalogsProductsGetByProductGroupFilters
    - App\Handler\Integrations
    - App\Handler\IntegrationsCommerce
    - App\Handler\IntegrationsCommerceExternalBusinessId
    - App\Handler\IntegrationsLogs
    - App\Handler\IntegrationsId
    - App\Handler\Media
    - App\Handler\MediaMediaId
    - App\Handler\OauthToken
    - App\Handler\Pins
    - App\Handler\PinsPinId
    - App\Handler\PinsPinIdAnalytics
    - App\Handler\PinsPinIdSave
    - App\Handler\ResourcesAdAccountCountries
    - App\Handler\ResourcesDeliveryMetrics
    - App\Handler\ResourcesLeadFormQuestions
    - App\Handler\ResourcesMetricsReadyState
    - App\Handler\ResourcesTargetingInterestsInterestId
    - App\Handler\ResourcesTargetingTargetingType
    - App\Handler\SearchBoards
    - App\Handler\SearchPartnerPins
    - App\Handler\SearchPins
    - App\Handler\TermsRelated
    - App\Handler\TermsSuggested
    - App\Handler\TrendsKeywordsRegionTopTrendType
    - App\Handler\UserAccount
    - App\Handler\UserAccountAnalytics
    - App\Handler\UserAccountAnalyticsTopPins
    - App\Handler\UserAccountAnalyticsTopVideoPins
    - App\Handler\UserAccountBusinesses
    - App\Handler\UserAccountFollowers
    - App\Handler\UserAccountFollowing
    - App\Handler\UserAccountFollowingBoards
    - App\Handler\UserAccountFollowingUsername
    - App\Handler\UserAccountWebsites
    - App\Handler\UserAccountWebsitesVerification
    - App\Handler\UsersUsernameInterestsFollow

Articus\PathHandler\Handler\PluginManager:
  abstract_factories:
  - Laminas\ServiceManager\AbstractFactory\ConfigAbstractFactory

#Articus\PathHandler\Consumer\PluginManager:
#  factories:
#  invokables:

#Articus\PathHandler\Attribute\PluginManager:
#  factories:
#  invokables:

#Articus\PathHandler\Producer\PluginManager:
#  factories:
#  invokables:

Laminas\ServiceManager\AbstractFactory\ConfigAbstractFactory:
  App\Handler\AdAccounts: []
  App\Handler\AdAccountsAdAccountId: []
  App\Handler\AdAccountsAdAccountIdAdGroups: []
  App\Handler\AdAccountsAdAccountIdAdGroupsAnalytics: []
  App\Handler\AdAccountsAdAccountIdAdGroupsAudienceSizing: []
  App\Handler\AdAccountsAdAccountIdAdGroupsTargetingAnalytics: []
  App\Handler\AdAccountsAdAccountIdAdGroupsAdGroupId: []
  App\Handler\AdAccountsAdAccountIdAdPreviews: []
  App\Handler\AdAccountsAdAccountIdAds: []
  App\Handler\AdAccountsAdAccountIdAdsAnalytics: []
  App\Handler\AdAccountsAdAccountIdAdsTargetingAnalytics: []
  App\Handler\AdAccountsAdAccountIdAdsAdId: []
  App\Handler\AdAccountsAdAccountIdAdsCreditDiscounts: []
  App\Handler\AdAccountsAdAccountIdAdsCreditRedeem: []
  App\Handler\AdAccountsAdAccountIdAnalytics: []
  App\Handler\AdAccountsAdAccountIdAudienceInsights: []
  App\Handler\AdAccountsAdAccountIdAudiences: []
  App\Handler\AdAccountsAdAccountIdAudiencesCustom: []
  App\Handler\AdAccountsAdAccountIdAudiencesAudienceId: []
  App\Handler\AdAccountsAdAccountIdBidFloor: []
  App\Handler\AdAccountsAdAccountIdBillingProfiles: []
  App\Handler\AdAccountsAdAccountIdBulkDownload: []
  App\Handler\AdAccountsAdAccountIdBulkUpsert: []
  App\Handler\AdAccountsAdAccountIdBulkBulkRequestId: []
  App\Handler\AdAccountsAdAccountIdCampaigns: []
  App\Handler\AdAccountsAdAccountIdCampaignsAnalytics: []
  App\Handler\AdAccountsAdAccountIdCampaignsTargetingAnalytics: []
  App\Handler\AdAccountsAdAccountIdCampaignsCampaignId: []
  App\Handler\AdAccountsAdAccountIdConversionTags: []
  App\Handler\AdAccountsAdAccountIdConversionTagsOcpmEligible: []
  App\Handler\AdAccountsAdAccountIdConversionTagsPageVisit: []
  App\Handler\AdAccountsAdAccountIdConversionTagsConversionTagId: []
  App\Handler\AdAccountsAdAccountIdCustomerLists: []
  App\Handler\AdAccountsAdAccountIdCustomerListsCustomerListId: []
  App\Handler\AdAccountsAdAccountIdEvents: []
  App\Handler\AdAccountsAdAccountIdInsightsAudiences: []
  App\Handler\AdAccountsAdAccountIdKeywords: []
  App\Handler\AdAccountsAdAccountIdKeywordsMetrics: []
  App\Handler\AdAccountsAdAccountIdLeadForms: []
  App\Handler\AdAccountsAdAccountIdLeadFormsLeadFormId: []
  App\Handler\AdAccountsAdAccountIdLeadFormsLeadFormIdTest: []
  App\Handler\AdAccountsAdAccountIdLeadsSubscriptions: []
  App\Handler\AdAccountsAdAccountIdLeadsSubscriptionsSubscriptionId: []
  App\Handler\AdAccountsAdAccountIdMmmReports: []
  App\Handler\AdAccountsAdAccountIdOrderLines: []
  App\Handler\AdAccountsAdAccountIdOrderLinesOrderLineId: []
  App\Handler\AdAccountsAdAccountIdProductGroupPromotions: []
  App\Handler\AdAccountsAdAccountIdProductGroupPromotionsProductGroupPromotionId: []
  App\Handler\AdAccountsAdAccountIdProductGroupsAnalytics: []
  App\Handler\AdAccountsAdAccountIdProductGroupsCatalogs: []
  App\Handler\AdAccountsAdAccountIdReports: []
  App\Handler\AdAccountsAdAccountIdSandbox: []
  App\Handler\AdAccountsAdAccountIdSsioAccounts: []
  App\Handler\AdAccountsAdAccountIdSsioInsertionOrders: []
  App\Handler\AdAccountsAdAccountIdSsioInsertionOrdersStatus: []
  App\Handler\AdAccountsAdAccountIdSsioInsertionOrdersPinOrderIdStatus: []
  App\Handler\AdAccountsAdAccountIdSsioOrderLines: []
  App\Handler\AdAccountsAdAccountIdTargetingAnalytics: []
  App\Handler\AdAccountsAdAccountIdTemplates: []
  App\Handler\AdAccountsAdAccountIdTemplatesTemplateIdReports: []
  App\Handler\AdAccountsAdAccountIdTermsOfService: []
  App\Handler\Boards: []
  App\Handler\BoardsBoardId: []
  App\Handler\BoardsBoardIdPins: []
  App\Handler\BoardsBoardIdSections: []
  App\Handler\BoardsBoardIdSectionsSectionId: []
  App\Handler\BoardsBoardIdSectionsSectionIdPins: []
  App\Handler\Catalogs: []
  App\Handler\CatalogsFeeds: []
  App\Handler\CatalogsFeedsFeedId: []
  App\Handler\CatalogsFeedsFeedIdProcessingResults: []
  App\Handler\CatalogsItems: []
  App\Handler\CatalogsItemsBatch: []
  App\Handler\CatalogsItemsBatchBatchId: []
  App\Handler\CatalogsProcessingResultsProcessingResultIdItemIssues: []
  App\Handler\CatalogsProductGroups: []
  App\Handler\CatalogsProductGroupsProductGroupId: []
  App\Handler\CatalogsProductGroupsProductGroupIdProductCounts: []
  App\Handler\CatalogsProductGroupsProductGroupIdProducts: []
  App\Handler\CatalogsProductsGetByProductGroupFilters: []
  App\Handler\Integrations: []
  App\Handler\IntegrationsCommerce: []
  App\Handler\IntegrationsCommerceExternalBusinessId: []
  App\Handler\IntegrationsLogs: []
  App\Handler\IntegrationsId: []
  App\Handler\Media: []
  App\Handler\MediaMediaId: []
  App\Handler\OauthToken: []
  App\Handler\Pins: []
  App\Handler\PinsPinId: []
  App\Handler\PinsPinIdAnalytics: []
  App\Handler\PinsPinIdSave: []
  App\Handler\ResourcesAdAccountCountries: []
  App\Handler\ResourcesDeliveryMetrics: []
  App\Handler\ResourcesLeadFormQuestions: []
  App\Handler\ResourcesMetricsReadyState: []
  App\Handler\ResourcesTargetingInterestsInterestId: []
  App\Handler\ResourcesTargetingTargetingType: []
  App\Handler\SearchBoards: []
  App\Handler\SearchPartnerPins: []
  App\Handler\SearchPins: []
  App\Handler\TermsRelated: []
  App\Handler\TermsSuggested: []
  App\Handler\TrendsKeywordsRegionTopTrendType: []
  App\Handler\UserAccount: []
  App\Handler\UserAccountAnalytics: []
  App\Handler\UserAccountAnalyticsTopPins: []
  App\Handler\UserAccountAnalyticsTopVideoPins: []
  App\Handler\UserAccountBusinesses: []
  App\Handler\UserAccountFollowers: []
  App\Handler\UserAccountFollowing: []
  App\Handler\UserAccountFollowingBoards: []
  App\Handler\UserAccountFollowingUsername: []
  App\Handler\UserAccountWebsites: []
  App\Handler\UserAccountWebsitesVerification: []
  App\Handler\UsersUsernameInterestsFollow: []
