dependencies:
  factories:
    Mezzio\Router\RouterInterface: Articus\PathHandler\RouteInjectionFactory
    Articus\PathHandler\MetadataProviderInterface: Articus\PathHandler\MetadataProvider\Factory\Annotation
    Articus\PathHandler\Handler\PluginManager: Articus\PathHandler\Handler\Factory\PluginManager
    Articus\PathHandler\Consumer\PluginManager: Articus\PathHandler\Consumer\Factory\PluginManager
    Articus\PathHandler\Attribute\PluginManager: Articus\PathHandler\Attribute\Factory\PluginManager
    Articus\PathHandler\Producer\PluginManager: Articus\PathHandler\Producer\Factory\PluginManager

Articus\PathHandler\RouteInjectionFactory:
  paths:
    '/v5':
    - App\Handler\AdAccounts
    - App\Handler\AdAccountsAdAccountIdAdGroups
    - App\Handler\AdAccountsAdAccountIdAdGroupsAnalytics
    - App\Handler\AdAccountsAdAccountIdAds
    - App\Handler\AdAccountsAdAccountIdAdsAnalytics
    - App\Handler\AdAccountsAdAccountIdAnalytics
    - App\Handler\AdAccountsAdAccountIdCampaigns
    - App\Handler\AdAccountsAdAccountIdCampaignsAnalytics
    - App\Handler\AdAccountsAdAccountIdProductGroupsAnalytics
    - App\Handler\AdAccountsAdAccountIdReports
    - App\Handler\Boards
    - App\Handler\BoardsBoardId
    - App\Handler\BoardsBoardIdPins
    - App\Handler\BoardsBoardIdSections
    - App\Handler\BoardsBoardIdSectionsSectionId
    - App\Handler\BoardsBoardIdSectionsSectionIdPins
    - App\Handler\CatalogsFeeds
    - App\Handler\CatalogsFeedsFeedId
    - App\Handler\CatalogsFeedsFeedIdProcessingResults
    - App\Handler\CatalogsItems
    - App\Handler\CatalogsItemsBatch
    - App\Handler\CatalogsItemsBatchBatchId
    - App\Handler\CatalogsProductGroups
    - App\Handler\CatalogsProductGroupsProductGroupId
    - App\Handler\Media
    - App\Handler\MediaMediaId
    - App\Handler\OauthToken
    - App\Handler\Pins
    - App\Handler\PinsPinId
    - App\Handler\PinsPinIdAnalytics
    - App\Handler\UserAccount
    - App\Handler\UserAccountAnalytics

Articus\PathHandler\Handler\PluginManager:
  abstract_factories:
  - Laminas\ServiceManager\AbstractFactory\ConfigAbstractFactory

#Articus\PathHandler\Consumer\PluginManager:
#  factories:
#  invokables:

#Articus\PathHandler\Attribute\PluginManager:
#  factories:
#  invokables:

#Articus\PathHandler\Producer\PluginManager:
#  factories:
#  invokables:

Laminas\ServiceManager\AbstractFactory\ConfigAbstractFactory:
  App\Handler\AdAccounts: []
  App\Handler\AdAccountsAdAccountIdAdGroups: []
  App\Handler\AdAccountsAdAccountIdAdGroupsAnalytics: []
  App\Handler\AdAccountsAdAccountIdAds: []
  App\Handler\AdAccountsAdAccountIdAdsAnalytics: []
  App\Handler\AdAccountsAdAccountIdAnalytics: []
  App\Handler\AdAccountsAdAccountIdCampaigns: []
  App\Handler\AdAccountsAdAccountIdCampaignsAnalytics: []
  App\Handler\AdAccountsAdAccountIdProductGroupsAnalytics: []
  App\Handler\AdAccountsAdAccountIdReports: []
  App\Handler\Boards: []
  App\Handler\BoardsBoardId: []
  App\Handler\BoardsBoardIdPins: []
  App\Handler\BoardsBoardIdSections: []
  App\Handler\BoardsBoardIdSectionsSectionId: []
  App\Handler\BoardsBoardIdSectionsSectionIdPins: []
  App\Handler\CatalogsFeeds: []
  App\Handler\CatalogsFeedsFeedId: []
  App\Handler\CatalogsFeedsFeedIdProcessingResults: []
  App\Handler\CatalogsItems: []
  App\Handler\CatalogsItemsBatch: []
  App\Handler\CatalogsItemsBatchBatchId: []
  App\Handler\CatalogsProductGroups: []
  App\Handler\CatalogsProductGroupsProductGroupId: []
  App\Handler\Media: []
  App\Handler\MediaMediaId: []
  App\Handler\OauthToken: []
  App\Handler\Pins: []
  App\Handler\PinsPinId: []
  App\Handler\PinsPinIdAnalytics: []
  App\Handler\UserAccount: []
  App\Handler\UserAccountAnalytics: []
